# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e995e89ad811de13db202c3e021ee8c1f9eec42284b7eb42c3a34562890f3c138d1ada757198901d2fd6cfd65c503b97470ba6e4705bafc99b989ae502606524

test:
  secret_key_base: 435c1f3fd127578eb73380cfdd4aed1cbde172851410c4113b9fff36b171814716edc8f475470c792184aaa4bacd761ea817fc06060a844708c84c523b9cc12d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
